{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "redisshake.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.sourcePassword }}
  source-password: {{ .Values.secret.sourcePassword | b64enc }}
  {{- end }}
  {{- if .Values.secret.targetPassword }}
  target-password: {{ .Values.secret.targetPassword | b64enc }}
  {{- end }}
{{- end }}
